name: Build on PR

on: 
  pull_request:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Prisma
        run: npm run db:generate

      - name: Run linting check
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check